### PR TITLE
[#72] Fix anchor generation of headers with spaces

### LINKED ISSUE #72: [BUG] Header anchors are prefixed with a dash
# Description

Say we have a header such as:

```md
## <a name="link-one"></a> Link two
```

This markdown is supposed to generate two anchors: `link-one` and `link-two`.

However, it looks like xrefcheck thinks the second anchor is `-link-two` (and not `link-two`).

See @alyoanton9's comment for a description of the issue and solution: https://github.com/serokell/xrefcheck/pull/68#discussion_r676461656

# To Reproduce

Create a markdown file with the following content, and then run `xrefcheck -r <filename>`

```md
## <a name="stuff-section"></a> Some stuff

[My link](#some-stuff)
```

# Expected behavior

`xrefcheck` should succeed.

# Actual behavior

`xrefcheck` fails:

```
=== Invalid references found ===

  ➥  In file tests/markdowns/without-annotations/anchors_in_headers.md
     bad reference (local) at src:9:1-22:
       - text: "My link"
       - link: 
       - anchor: some-stuff
     
     ⛀  Anchor 'some-stuff' is not present,
        did you mean -some-stuff (header II) at src:7:1-42?
```

# Environment

- branch: slowpnir/anchors-in-headers

### PR DESCRIPTION
**Pull request by breakerzirconia**
## Description

Problem: 
A header name with its custom anchor appended after the octothorpe symbol(s) is parsed with the leading spaces present, thus generating an anchor from it will result in having a leading hyphen prepended to its beginning.

Solution: 
Having retrieved the header name, strip it to eradicate the leading spaces. This will result in the correct generation of the anchor which won't contain a hyphen at its beginning.

## Related issue(s)

Resolves #72 by applying `Data.Text.strip` to the extracted name of either a link or a header in `nodeExtractText`.

## :white_check_mark: Checklist for your Pull Request

Ideally a PR has all of the checkmarks set.

If something in this list is irrelevant to your PR, you should still set this
checkmark indicating that you are sure it is dealt with (be that by irrelevance).

#### Related changes (conditional)

- Tests
  - [x] If I added new functionality, I added tests covering it.
  - [x] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

- Documentation
  - [x] I checked whether I should update the docs and did so if necessary:
    - [README](/README.md)
    - Haddock

- Public contracts
  - [x] Any modifications of public contracts comply with the [Evolution
  of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public-Contracts-2a3bf7971abe4806a24f63c84e7076c5) policy.
  - [ ] I added an entry to the [changelog](/CHANGES.md) if my changes are visible to the users
        and
  - [x] provided a migration guide for breaking changes if possible

#### Stylistic guide (mandatory)

- [x] My commits comply with [the policy used in Serokell](https://www.notion.so/serokell/Where-and-how-to-commit-your-work-58f8973a4b3142c8abbd2e6fd5b3a08e).
- [x] My code complies with the [style guide](docs/code-style.md).

### CODE REVIEW

File: tests/Test/Xrefcheck/AnchorsSpec.hs [hunk 1]
```diff
@@ -5,18 +5,37 @@
...
+                               ]
+  where
+    parse :: FilePath -> IO (Either Text FileInfo)
+    parse path =
+      parseFileInfo MarkdownConfig{ mcFlavor = fl } . decodeUtf8 <$> BSL.readFile path
+
+    getFI :: FilePath -> IO FileInfo
+    getFI path =
+      let errOrFI = parse path
+      in either error id <$> errOrFI
```
Comment (Martoon-00) [inline tests/Test/Xrefcheck/AnchorsSpec.hs:35]: Oh, I suspect that this is copied from another place.

Could you please create an `Util` module in tests and place this reading function there?

**Review by Martoon-00 — APPROVED** [review]
Looks good to me :+1: 

Just left one minor comment.

File: tests/Test/Xrefcheck/AnchorsSpec.hs (hunk 1 above)
Comment (breakerzirconia) [reply tests/Test/Xrefcheck/AnchorsSpec.hs:35]: Absolutely.

Comment (breakerzirconia) [reply tests/Test/Xrefcheck/AnchorsSpec.hs:35]: Hmm, on another note, the definitions of `parse` slightly differ in the respective test modules: in `AnchorSpec` `parse` depends on the `Flavor` in the local scope, but in `IgnoreAnnotationSpec` it doesn't and uses the default GitHub configuration. May I use the default config in `AnchorSpec` as well (for the test's primary purpose is to ensure that there are no leading hyphens, which works for both `Flavor`s) to then put `parse`, `getAnchors` and `getFI` in the `Util` module?

Comment (Martoon-00) [reply tests/Test/Xrefcheck/AnchorsSpec.hs:35]: I personally would make the function accept `Flavor` explicitly because generally there is no sense of "default" flavor. 

The one who writes his own test should decide, whether can he test that on just one arbitrary flavor or try every possible flavor, and it's good if we force him to take this decision.

**Review by dcastro — APPROVED** [review]
LGTM, well done! :+1:
