### PR TITLE
[#55] GitLab support

### LINKED ISSUE #55: [BUG] Support Gitlab's header-to-anchor conversion properly
# Description

When I implemented anchors derivation from headers, I used Github as an example, thinking that since both Github and Gitlab are using CommonMark, they should behave in the same way. And meh, I was wrong.

While `A & B` or `A / B` are translated to `a--b` anchor in Github, in Gilab the result will be just `a-b`.

# To Reproduce

Make a page with `A & B` header and `#a-b` / `#a--b` anchors. The former is treated as a valid anchor, not the later, which is wrong for Gitlab repositories.

# Expected behavior

Behaviour for the mentioned anchors should be the opposite.

# Environment

- Ubuntu
- `5ba3605a`

### PR DESCRIPTION
**Pull request by Martoon-00**
## Description

It turned out that anchors generated from headers have minor differences in GitHub and GitLab, we handle this here.

## Related issue(s)

Resolves #55 

## :white_check_mark: Checklist for your Pull Request

Ideally a PR has all of the checkmarks set.

If something in this list is irrelevant to your PR, you should still set this
checkmark indicating that you are sure it is dealt with (be that by irrelevance).

#### Related changes (conditional)

- Tests
  - [x] If I added new functionality, I added tests covering it.
  - [x] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

- Documentation
  - [x] I checked whether I should update the docs and did so if necessary:
    - [README](/README.md)
    - Haddock

- Public contracts
  - [ ] Any modifications of public contracts comply with the [Evolution
  of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public-Contracts-2a3bf7971abe4806a24f63c84e7076c5) policy.
  - [x] I added an entry to the [changelog](/CHANGES.md) if my changes are visible to the users
        and
  - [x] provided a migration guide for breaking changes if possible

#### Stylistic guide (mandatory)

- [x] My commits comply with [the policy used in Serokell](https://www.notion.so/serokell/Where-and-how-to-commit-your-work-58f8973a4b3142c8abbd2e6fd5b3a08e).
- [x] My code complies with the [style guide](docs/code-style.md).

### CODE REVIEW

**Review by alyoanton9 — COMMENTED** [review]
LGTM, from what I can tell (with my experience).

I just wish you to answer my questions in the comments on code.

File: src/Xrefcheck/Config.hs [hunk 1]
```diff
@@ -7,33 +7,38 @@
 
 module Xrefcheck.Config where
 
+import qualified Unsafe
```
[the remark this answers is not in the document]
Comment (Martoon-00) [reply src/Xrefcheck/Config.hs:10]: We [tend](https://gitlab.com/morley-framework/morley/-/blob/master/docs/code-style.md#imports) to group imports, prelude-related first, then third party libraries, then local packages. `Unsafe` is from prelude, so appears at the top.

File: src/Xrefcheck/Config.hs [hunk 2]
```diff
@@ -57,18 +65,119 @@ makeLensesWith postfixFields ''VerifyConfig
...
+      assert (off > processedLen) $
+        pickConfigSubstring processedLen (off - processedLen) :
+        replaceHole (pickConfigSubstring off len) ++
+        replaceHoles (off + len) locs
+
+    holeItemRegex :: R.Regex
+    holeItemRegex = R.makeRegex ("(^|:)([ ]*):PLACEHOLDER:([^:]+):" :: Text)
+
+    holeListRegex :: R.Regex
+    holeListRegex = R.makeRegex ("^([ ]*-[ ]*):PLACEHOLDER:([^:]+):" :: Text)
```
[the remark this answers is not in the document]
Comment (Martoon-00) [reply src/Xrefcheck/Config.hs:112]: I supposed that list hole allows inserting a list of entries, for instance [`virtualFiles`](https://github.com/serokell/xrefcheck/pull/57/files#diff-5b93233819d5f91ba783808ea00b7ec4f93d64c58b6b2d1b38e11d692facbd52R34) is now defined as a list placeholder.

[the remark this answers is not in the document]
Comment (alyoanton9) [reply src/Xrefcheck/Config.hs:112]: Yeah, it's clear. I mean that `:PLACEHOLDER:virtualFiles` and, for example, `:PLACEHOLDER:repositoryType` can be matched with `holeItemRegex`, and it seems that the hole always looks like `:PLACEHOLDER:name`, where `name` is just sequence of characters and numbers(?). So that I can't catch why we need 2 different regex and ask for an example.

[the remark this answers is not in the document]
Comment (Martoon-00) [reply src/Xrefcheck/Config.hs:112]: Ah, I see.

Well, in the case of the list, I need to prepend each entry with a `-`. And it is not trivial to figure out automatically where this `-` should be, because yaml has to be properly indented, and indentation may differ depending on the practices used in this particular file. So the simplest I can do is to assume that the placeholder is also prepended with `-` and replicate this `-` at whatever indentation it is.

So the difference is that for lists I expect this `-` before the placeholder, and for single entries the is no such prefix. It turned out that fetching the `-` was simpler with regexps.

[the remark this answers is not in the document]
Comment (alyoanton9) [reply src/Xrefcheck/Config.hs:112]: Oooh, I see now. Thanks!

**Review by alyoanton9 — APPROVED** [review]

File: src-files/def-config.yaml [hunk 3]
```diff
@@ -56,3 +56,12 @@ verification:
...
     []
+
+# Parameters of scanners for various file types.
+scanners:
+
+  markdown:
+    # Type of repository.
+    #
+    # This affects which anchors are generated for headers.
+    repositoryType: GitHub
```
Comment (gromakovsky) [inline src-files/def-config.yaml]: Maybe let's call it `flavor` or `format` or something like that? There are various specifications of markdown: [CommonMark](https://commonmark.org/) is probably the most popular basic specification and GitHub-flavored markdown is an extension of it. GitLab-flavored markdown is another extension of CommonMark (it's CommonMark + some stuff AFAIK). So I think we are interested not in _repository type_ or _service where you push your repository_, but rather in markdown flavor that you follow. For example, if you use neither GitLab nor GitHub, there is still a chance that your service mandates GitHub-flavored markdown for example, so it will make sense to write `flavor: GitHub`, but less sense to write `repositoryType: GitHub`.

In future versions I guess we can also support `flavor: CommonMark` here for example.

File: src/Xrefcheck/Core.hs [hunk 4]
```diff
@@ -38,6 +38,14 @@ data RepoType
   | GitLab
   deriving (Show)
 
+allRepoTypes :: [RepoType]
+allRepoTypes = [GitHub, GitLab]
```
Comment (gromakovsky) [inline src/Xrefcheck/Core.hs:42]: Btw, you could also use `Bounded` and `Enum` I suppose.

File: src-files/def-config.yaml (hunk 3 above)
Comment (Martoon-00) [reply src-files/def-config.yaml]: Hmm, sounds pretty good, gonna do.

File: src/Xrefcheck/Core.hs (hunk 4 above)
Comment (Martoon-00) [reply src/Xrefcheck/Core.hs:42]: Yeah, I wanted to do so first, but then imagined that there can be some GitHub-specific settings in the future (some field in `GitHub` ctor), so preferred to go with this thing from the beginning.

File: src/Xrefcheck/CLI.hs [hunk 5]
```diff
@@ -47,7 +47,7 @@ modeReadM = eitherReader $ \s ->
 
 data Command
   = DefaultCommand Options
-  | DumpConfig RepoType FilePath
+  | DumpConfig Flavor FilePath
```
Comment (gromakovsky) [inline src/Xrefcheck/CLI.hs:50]: And for this command it actually makes sense to take `RepoType` rather than `Flavor`. Currently these are equal sets (of repo types and MD flavors), but one day we may support another repo type that may use an existing flavor (e. g. GH-flavored MD). Then `RepoType` will become a different entity and it will be appropriate here. That repo type may also have different `notScanned` and `virtualFiles` for example.

That said, I don't think it's _necessary_ to bother with this stuff _now_, I am just pointing it out. So I think that `RepoType` and `Flavor` are 2 different entities, currently they would be equal and we use `Flavor` to denote `RepoType` also and that's fine for now.

**Review by gromakovsky — APPROVED** [review]
I reviewed superficially, didn't check complex logic.

File: src/Xrefcheck/CLI.hs (hunk 5 above)
Comment (Martoon-00) [reply src/Xrefcheck/CLI.hs:50]: Yeah, at least half of me also thinks so.

I guess I'll leave a comment about this distinction and rename the CLI option.
