### PR TITLE
[#90] Forbid verifying a single file

### LINKED ISSUE #90: [BUG] Wrong path when verifying a single file
# Description

The `-r` option allows specifying a single file (e.g. `xrefcheck -r README.md`).

However, if that file references other local files (e.g. `./X.md`) it looks like the root file is then prepended to their paths (`README.md/./X.md`), and so some checks may fail.

# To Reproduce

Run this command in the repo's root:

```
$ xrefcheck -r README.md                                           
Configuration file not found, using default config for GitHub repositories

=== Invalid references found ===                                                                                                                                                         

  ➥  In file ./README.md
     bad reference (absolute) at src:193:12-54:
       - text: "CONTRIBUTING.md"
       - link: /.github/CONTRIBUTING.md
       - anchor: -
     
     ⛀  File does not exist:
        README.md/.github/CONTRIBUTING.md
     
     
Invalid references dumped, 1 in total.
```

Notice the `README.md/.github/CONTRIBUTING.md` in the error message.

# Expected behavior

Expected file to be valid.

# Environment

- master, f8bb96c8a91b801336d43e02a2358dbe222e60be

### PR DESCRIPTION
**Pull request by nalkuatov**
This adds some bytes to forbid verifying a single file.

## Related issue(s)

Resolves #90 

## :white_check_mark: Checklist for your Pull Request

Ideally a PR has all of the checkmarks set.

If something in this list is irrelevant to your PR, you should still set this
checkmark indicating that you are sure it is dealt with (be that by irrelevance).

#### Related changes (conditional)

- Tests
  - [x] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

- Documentation
  - [ ] I checked whether I should update the docs and did so if necessary:
    - [README](/README.md)
    - Haddock

- Public contracts
  - [ ] Any modifications of public contracts comply with the [Evolution
  of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public-Contracts-2a3bf7971abe4806a24f63c84e7076c5) policy.
  - [x] I added an entry to the [changelog](/CHANGES.md) if my changes are visible to the users
        and
  - [ ] provided a migration guide for breaking changes if possible

#### Stylistic guide (mandatory)

- [x] My commits comply with [the policy used in Serokell](https://www.notion.so/serokell/Where-and-how-to-commit-your-work-58f8973a4b3142c8abbd2e6fd5b3a08e).
- [x] My code complies with the [style guide](/docs/code-style.md).

### CODE REVIEW

File: tests/Test/Xrefcheck/TrailingSlashSpec.hs [hunk 1]
```diff
@@ -45,6 +45,4 @@ spec = do
       [ "tests/markdowns/without-annotations"
       , "tests/markdowns/without-annotations/"
       , "tests/markdowns/without-annotations/./"
-      , "tests/markdowns/without-annotations/all_checked.md"
-      , "tests/markdowns/without-annotations/./all_checked.md"
```
Comment (dcastro) [inline tests/Test/Xrefcheck/TrailingSlashSpec.hs:49]: Why were these tests removed?

File: src/Xrefcheck/Scan.hs [hunk 2]
```diff
@@ -23,11 +23,13 @@ import Data.Aeson.TH (deriveFromJSON)
 import Data.Foldable qualified as F
```
Comment (dcastro) [inline src/Xrefcheck/Scan.hs:23]: Please add a golden tests for this (see the `tests/golden` folder)

Comment (dcastro) [inline src/Xrefcheck/Scan.hs:23]: Please go through the PR checklist.
Since this PR affects the user, we should update the changelog.

File: src/Xrefcheck/Scan.hs [hunk 3]
```diff
@@ -64,6 +66,10 @@ gatherRepoInfo
   => Rewrite -> FormatsSupport -> TraversalConfig -> FilePath -> m RepoInfo
 gatherRepoInfo rw formatsSupport config root = do
   putTextRewrite rw "Scanning repository..."
+
+  when (not $ isDirectory root) $
+    errorWithoutStackTrace $ "Repository's root does not seem to be a directory"
```
Comment (dcastro) [inline src/Xrefcheck/Scan.hs:71]: `die` is more idiomatic than `errorWithoutStackTrace` here.

Comment (dcastro) [inline src/Xrefcheck/Scan.hs:71]: Let's also print the value of `root`

```suggestion
    errorWithoutStackTrace $ "Repository's root does not seem to be a directory: " <> root
```

**Review by dcastro — CHANGES_REQUESTED** [review]

File: tests/Test/Xrefcheck/TrailingSlashSpec.hs (hunk 1 above)
Comment (nalkuatov) [reply tests/Test/Xrefcheck/TrailingSlashSpec.hs:49]: These paths seem to be passed as `root`s while gathering repo info. Since now we forbid verifying a single file as `root`, these paths fail the test

File: tests/golden/check-cli/check-cli.bats [hunk 4]
```diff
@@ -77,3 +77,10 @@ load '../helpers'
 
   rm /tmp/check-cli.test
 }
+
+@test "Single file as root" {
+  run xrefcheck \
+    --root single-file.md
+
+  assert_output --partial "Repository's root does not seem to be a directory: single-file.md"
```
Comment (dcastro) [inline tests/golden/check-cli/check-cli.bats:85]: Let's:
* add `assert_failure` to check that the application exited with a non-zero status code.
* remove `--partial`, because we don't expect anything else to be printed to stdout

```suggestion
  assert_failure
  assert_output "Repository's root does not seem to be a directory: single-file.md"
```

File: tests/Test/Xrefcheck/TrailingSlashSpec.hs (hunk 1 above)
Comment (dcastro) [reply tests/Test/Xrefcheck/TrailingSlashSpec.hs:49]: Ah right, makes sense!

**Review by dcastro — APPROVED** [review]
Just one minor final comment ^^ pre-approving anyway

File: tests/golden/check-cli/check-cli.bats (hunk 4 above)
Comment (nalkuatov) [reply tests/golden/check-cli/check-cli.bats:85]: > remove --partial, because we don't expect anything else to be printed to stdout

Turns out that [`assert_output` captures stderr too](https://bats-core.readthedocs.io/en/stable/faq.html?highlight=assert_output#how-do-i-see-the-output-of-the-command-under-run-when-a-test-fails) :) 

So the output seems to contain 4 lines, including `Configuration file not found, using default config for GitHub repositories`
