### PR TITLE
[#49] Allow certain reserved characters in the URLs

### LINKED ISSUE #49: [BUG] Urls with `[` and `]` fail to parse
# Description

When a link contains braces, xrefcheck reports that as bad url.

# To Reproduce

Have the following link: 

This results in

```
  ➥  In file ./code/indigo/tutorial/docs/index.md
     bad reference (external) at src:66:12-120:
       - text: "new GitLab issue"
       - link: https://gitlab.com/morley-framework/morley/-/issues/new?issue[title]=Indigo%20website:%20
       - anchor: -
     ⛂  Invalid url
```

# Expected behavior

Everything passes.

# Environment

- Ubuntu
- 5ba3605ac7c5fc5da4f0474bcc04855a61265714

### PR DESCRIPTION
**Pull request by breakerzirconia**
## Description

Problem: The current version of xrefcheck doesn't allow the square
brackets and some other special characters, like the angle brackets and
the curly brackets, to be present in the URLs, even in the query
strings, as they need to be percent-encoded first.

Solution: Allow some of the reserved characters, like the brackets, to
be present in the query strings of the URLs.
There exist two main standards of URL parsing: RFC 3986 and the Web
Hypertext Application Technology Working Group's URL standard. Ideally,
we want to be able to parse the URLs in accordance with the latter
standard, because it provides a much less ambiguous set of rules for
percent-encoding special characters, and is essentially a living
standard that gets updated constantly.
We allow these characters to be present in the query strings by using
the `parseURI` function from the `uri-bytestring` library with
`laxURIParseOptions`.

## Related issue(s)

Fixes #49

## :white_check_mark: Checklist for your Pull Request

Ideally a PR has all of the checkmarks set.

If something in this list is irrelevant to your PR, you should still set this
checkmark indicating that you are sure it is dealt with (be that by irrelevance).

#### Related changes (conditional)

- Tests
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

- Documentation
  - [x] I checked whether I should update the docs and did so if necessary:
    - [README](/README.md)
    - Haddock

- Public contracts
  - [ ] Any modifications of public contracts comply with the [Evolution
  of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public-Contracts-2a3bf7971abe4806a24f63c84e7076c5) policy.
  - [x] I added an entry to the [changelog](/CHANGES.md) if my changes are visible to the users
        and
  - [x] provided a migration guide for breaking changes if possible

#### Stylistic guide (mandatory)

- [x] My commits comply with [the policy used in Serokell](https://www.notion.so/serokell/Where-and-how-to-commit-your-work-58f8973a4b3142c8abbd2e6fd5b3a08e).
- [x] My code complies with the [style guide](/docs/code-style.md).

### CODE REVIEW

File: src/Xrefcheck/Verify.hs [hunk 1]
```diff
@@ -423,7 +424,11 @@ checkExternalResource :: VerifyConfig -> Text -> IO (VerifyResult VerifyError)
 checkExternalResource VerifyConfig{..} link
   | skipCheck = return mempty
   | otherwise = fmap toVerifyRes $ runExceptT $ do
-      uri <- mkURI link & maybe (throwError ExternalResourceInvalidUri) pure
+      uri' <- URIBS.parseURI URIBS.laxURIParserOptions (encodeUtf8 link)
```
Comment (dcastro) [inline src/Xrefcheck/Verify.hs:427]: Let's also add a test to make sure links with `[` and `]` are properly processed.

**Review by dcastro — CHANGES_REQUESTED** [review]

File: tests/Test/Xrefcheck/URIParsingSpec.hs [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+
+parse :: Text -> Either URIBS.URIParseError (URIBS.URI)
+parse link = URIBS.parseURI URIBS.laxURIParserOptions (encodeUtf8 link)
+
+spec :: Spec
+spec = do
+  describe "URI parsing should be successful" $ do
+    it "Without the special characters in the query strings" $
+      forM_ withoutSpecChars $ \link -> do
+        assertBool "Failed to parse the link" (isRight $ parse link)
```
Comment (dcastro) [inline tests/Test/Xrefcheck/URIParsingSpec.hs:22]: Well, looks like these tests are testing the local `parse` function... they're not testing xrefcheck.

If the code in `Verify` changes, this test will continue passing. We won't catch any possible bugs.

Comment (dcastro) [reply tests/Test/Xrefcheck/URIParsingSpec.hs:22]: I suggest extracting those two lines in `checkExternalResource` into a top-level function, e.g. `parseURL :: Text -> ExceptT VerifyError IO URI`, and then export that function so it can be tested here.

**Review by dcastro — CHANGES_REQUESTED** [review]

File: tests/Test/Xrefcheck/URIParsingSpec.hs (hunk 2 above)
Comment (dcastro) [inline tests/Test/Xrefcheck/URIParsingSpec.hs:22]: Also, let's not just check that the parse is successful (with `isRight`).

Let's check that it does indeed return the correct URI. I think you should be able to use the `uri` quasiquoter to express what the result should be: https://hackage.haskell.org/package/modern-uri-0.3.4.4/docs/Text-URI-QQ.html

File: tests/Test/Xrefcheck/URIParsingSpec.hs [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+
+import Xrefcheck.Verify (parseUri, VerifyError (..))
+
+spec :: Spec
+spec = do
+  describe "URI parsing should be successful" $ do
+    it "Without the special characters in the query strings" do
+      parsed <- traverse parseUri' withoutSpecChars
+      assertBool "Failed to parse the link"
+        $ parsed == withoutSpecCharsExpected
```
Comment (dcastro) [inline tests/Test/Xrefcheck/URIParsingSpec.hs:25]: Instead of using `assertBool msg $ x == y`, let's use ``x `shouldBe` y``, as it gives us much better error messages (i.e. `assertBool` just prints a generic error message, `shouldBe` prints the expected and the actual values as well)

Comment (dcastro) [reply tests/Test/Xrefcheck/URIParsingSpec.hs:25]: In fact, I think these tests could be written more succinctly (and with less indirection, and more readable) like this:

```hs
    it "Without the special characters in the query strings" do
      parseUri' "https://example.com/?q=a&p=b#fragment" `shouldReturn`
        Right [uri|https://example.com/?q=a&p=b#fragment|]

      parseUri' "https://example.com/path/to/smth?q=a&p=b" `shouldReturn`
        Right [uri|https://example.com/path/to/smth?q=a&p=b|]
```

**Review by dcastro — CHANGES_REQUESTED** [review]

**Review by dcastro — APPROVED** [review]
